### ISSUE TITLE
果然，这机子还有救

### ISSUE THREAD

**Issue by Tang1124** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#1]
战神Z7M CT5NA报道，有时间了试试，但是能不能告诉我刷原生BIOS咋搞啊，当前BIOS咋备份🤣

**Comment by MichaelPan1026** [comment]
我用的这个 bios，当然有更新的。http://repo.palkeo.com/clevo-mirror/NH5x_70_RDx_RCx_RAx_RHx(Q)/NHxxRC_RDx_B10713.zip

**Comment by Clement233** [comment]
老哥，z7mct5na不行啊，怎么搞？

**Comment by MichaelPan1026** [comment]
> 老哥，z7mct5na不行啊，怎么搞？

是怎么不行

**Comment by Clement233** [comment]
一直卡在白苹果logo

**Comment by MichaelPan1026** [comment]
> 一直卡在白苹果logo

bios设置改了没有 系统版本是什么

**Comment by ilworkcn** [comment]
> 一直卡在白苹果logo

引导参数加个 -v把照片发过来看看

**Comment by Clement233** [comment]
改了，刷了你分享出来的bios

**Comment by Clement233** [comment]
> > 一直卡在白苹果logo
> 
> 引导参数加个 -v把照片发过来看看

对不起，请问进不去mac怎么添加-v？

**Comment by MichaelPan1026** [comment]
> > > 一直卡在白苹果logo
> > 
> > 
> > 引导参数加个 -v把照片发过来看看
> 
> 对不起，请问进不去mac怎么添加-v？

我的问题 等下 昨天commit错版本了 抱歉

**Comment by ilworkcn** [comment]
> > > 一直卡在白苹果logo
> 
> > 
> 
> > 引导参数加个 -v把照片发过来看看
> 
> 
> 
> 对不起，请问进不去mac怎么添加-v？

github上qtopencoreconfig
项目 在Windows下编辑config.plist

**Comment by Clement233** [comment]
> > > > 一直卡在白苹果logo
> > > 
> > > 
> > > 引导参数加个 -v把照片发过来看看
> > 
> > 
> > 对不起，请问进不去mac怎么添加-v？
> 
> 我的问题 等下 昨天commit错版本了 抱歉

大佬能把OC分享出来就很棒了

**Comment by Clement233** [comment]
> > > > 一直卡在白苹果logo
> > 
> > 
> > > 
> > 
> > 
> > > 引导参数加个 -v把照片发过来看看
> > 
> > 
> > 对不起，请问进不去mac怎么添加-v？
> 
> github上qtopencoreconfig
> 项目 在Windows下编辑config.plist

我可以用notepad＋＋编辑，但要修改那里呢？

**Comment by Clement233** [comment]
> > > > 一直卡在白苹果logo
> > 
> > 
> > > 
> > 
> > 
> > > 引导参数加个 -v把照片发过来看看
> > 
> > 
> > 对不起，请问进不去mac怎么添加-v？
> 
> github上qtopencoreconfig
> 项目 在Windows下编辑config.plist

![2020-09-21_20 20 41](https://user-images.githubusercontent.com/54034022/93765735-e7f6c780-fc04-11ea-8271-8d435e86b739.jpg)
跑码如下，怎么搞，谢谢

**Comment by MichaelPan1026** [comment]
> > > > > 一直卡在白苹果logo
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 引导参数加个 -v把照片发过来看看
> > > 
> > > 
> > > 对不起，请问进不去mac怎么添加-v？
> > 
> > 
> > github上qtopencoreconfig
> > 项目 在Windows下编辑config.plist
> 
> ![2020-09-21_20 20 41](https://user-images.githubusercontent.com/54034022/93765735-e7f6c780-fc04-11ea-8271-8d435e86b739.jpg)
> 跑码如下，怎么搞，谢谢

你有在 bios 中关闭 CFG Lock 吗？

**Comment by Clement233** [comment]
> > > > > > 一直卡在白苹果logo
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 引导参数加个 -v把照片发过来看看
> > > > 
> > > > 
> > > > 对不起，请问进不去mac怎么添加-v？
> > > 
> > > 
> > > github上qtopencoreconfig
> > > 项目 在Windows下编辑config.plist
> > 
> > 
> > ![2020-09-21_20 20 41](https://user-images.githubusercontent.com/54034022/93765735-e7f6c780-fc04-11ea-8271-8d435e86b739.jpg)
> > 跑码如下，怎么搞，谢谢
> 
> 你有在 bios 中关闭 CFG Lock 吗？

这个机子好像没有CFG Lock的选项

**Comment by ilworkcn** [comment]
> > > > > > > 一直卡在白苹果logo
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > 
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > 引导参数加个 -v把照片发过来看看
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 对不起，请问进不去mac怎么添加-v？
> 
> > > > 
> 
> > > > 
> 
> > > > github上qtopencoreconfig
> 
> > > > 项目 在Windows下编辑config.plist
> 
> > > 
> 
> > > 
> 
> > > ![2020-09-21_20 20 41](https://user-images.githubusercontent.com/54034022/93765735-e7f6c780-fc04-11ea-8271-8d435e86b739.jpg)
> 
> > > 跑码如下，怎么搞，谢谢
> 
> > 
> 
> > 你有在 bios 中关闭 CFG Lock 吗？
> 
> 
> 
> 这个机子好像没有CFG Lock的选项

1.config.plist ->UEFI ->Quirks ->IgnoreInvalidFlexRatio ->True/YES

2.如果1中已经启用，还是卡这里，则需要启用config.plist ->Kernel ->Quirks ->AppleCpuPmCfgLock/AppleXcpmCfgLock ->True/YES

**Comment by Clement233** [comment]
> > > > > > > > 一直卡在白苹果logo
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > 引导参数加个 -v把照片发过来看看
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > 对不起，请问进不去mac怎么添加-v？
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > github上qtopencoreconfig
> > 
> > 
> > > > > 项目 在Windows下编辑config.plist
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > ![2020-09-21_20 20 41](https://user-images.githubusercontent.com/54034022/93765735-e7f6c780-fc04-11ea-8271-8d435e86b739.jpg)
> > 
> > 
> > > > 跑码如下，怎么搞，谢谢
> > 
> > 
> > > 
> > 
> > 
> > > 你有在 bios 中关闭 CFG Lock 吗？
> > 
> > 
> > 这个机子好像没有CFG Lock的选项
> 
> 1.config.plist ->UEFI ->Quirks ->IgnoreInvalidFlexRatio ->True/YES
> 
> 2.如果1中已经启用，还是卡这里，则需要启用config.plist ->Kernel ->Quirks ->AppleCpuPmCfgLock/AppleXcpmCfgLock ->True/YES

根据你的提示（两个都打开）已成功驱动苹果，更换OC后体验了一番，发现一个问题，就是触摸板的左右物理按键不能使用，不知道可以解决吗？还有就是英特尔的无线网卡真的不能驱动吗？最后就是谢谢两位大佬的帮助！如果可以，希望将修改后的config.plist文件在Github进行替换😊

**Comment by MichaelPan1026** [comment]
> > > > > > > > > 一直卡在白苹果logo
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > 引导参数加个 -v把照片发过来看看
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > 对不起，请问进不去mac怎么添加-v？
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > > github上qtopencoreconfig
> > > 
> > > 
> > > > > > 项目 在Windows下编辑config.plist
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > ![2020-09-21_20 20 41](https://user-images.githubusercontent.com/54034022/93765735-e7f6c780-fc04-11ea-8271-8d435e86b739.jpg)
> > > 
> > > 
> > > > > 跑码如下，怎么搞，谢谢
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 你有在 bios 中关闭 CFG Lock 吗？
> > > 
> > > 
> > > 这个机子好像没有CFG Lock的选项
> > 
> > 
> > 1.config.plist ->UEFI ->Quirks ->IgnoreInvalidFlexRatio ->True/YES
> > 2.如果1中已经启用，还是卡这里，则需要启用config.plist ->Kernel ->Quirks ->AppleCpuPmCfgLock/AppleXcpmCfgLock ->True/YES
> 
> 根据你的提示（两个都打开）已成功驱动苹果，更换OC后体验了一番，发现一个问题，就是触摸板的左右物理按键不能使用，不知道可以解决吗？还有就是英特尔的无线网卡真的不能驱动吗？最后就是谢谢两位大佬的帮助！如果可以，希望将修改后的config.plist文件在Github进行替换😊

左右按键解决不了也不用解决 英特尔的无线网卡在远景[有帖子](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1848662&mobile=yes)
