### ISSUE TITLE
g8-ct7na minidp fix

### ISSUE THREAD

**Issue by Gh-mean** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#10]

**Comment by Gh-mean** [comment]
希望能修复一下minidp的视频输出

**Comment by MichaelPan1026** [comment]
minidp 输出在我的机器上是完全正常的，没有实机不太好弄的。

**Comment by Gh-mean** [comment]
> minidp 输出在我的机器上是完全正常的，没有实机不太好弄的。

能教我如何修复吗？我这边插上dp口电脑就很卡一段时间

**Comment by Gh-mean** [comment]
<img width="721" alt="截屏2020-11-19 下午4 12 20" src="https://user-images.githubusercontent.com/48746903/99639027-11579680-2a82-11eb-906a-afb56464a1d2.png">
总线id：2456均修改使用过都无法驱动minidp口，不知道是什么问题

**Comment by MichaelPan1026** [comment]
> <img alt="截屏2020-11-19 下午4 12 20" width="721" src="https://user-images.githubusercontent.com/48746903/99639027-11579680-2a82-11eb-906a-afb56464a1d2.png">
> 
> 总线id：2456均修改使用过都无法驱动minidp口，不知道是什么问题

你先可以试试换机型的，我的机子 15 寸不能外接，13 寸就可以外接了。efi 默认是 13 寸的，你用 15 寸试试看。
