### ISSUE TITLE
大佬用的什么驱动的wifi

### ISSUE THREAD

**Issue by qianmoxiaowei** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#11]
我发现任务栏只有图标还有打开状态，但是搜索不到wifi

**Comment by MichaelPan1026** [comment]
我更换网卡了。自带网卡的话需要用到 [AirportItlwm](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0-alpha)

**Comment by qianmoxiaowei** [comment]
> 我更换网卡了。自带网卡的话需要用到 [AirportItlwm](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0-alpha)。

itlwm和airportitlwm的区别是前面那个只能用第三方客户端，第二个可以用原生的wifi，我试过把这两个驱动都启用，airportitlwm是没效果的，然后只启用airportitlwm的话，原生的wifi管理是好的，但是我感觉网速没有itlwm快呢。。。有没有同时启用的办法

**Comment by MichaelPan1026** [comment]
没有同时启用的方法。

「qianmoxiaowei <notifications@github.com>」在 2020年11月22日 週日，18:56 寫道：
