### ISSUE TITLE
请问有遇到关机花屏的问题吗？有什么解决方法吗？

### ISSUE THREAD

**Issue by WUYUEZONG** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#14]
如题！
使用命令开启 hidpi后，关机会有花屏现象。不使用hidpi正常。
OC版本：最新0.6.4版本
机型：Z8 - CT7NT
问题（如图）：

![WechatIMG8](https://user-images.githubusercontent.com/19921783/102017920-b412e480-3da4-11eb-8f04-2b576e683807.jpeg)

**Comment by MichaelPan1026** [comment]
开启了 hidpi 的话很正常

**Comment by WUYUEZONG** [comment]
> 开启了 hidpi 的话很正常

哦哦，这样啊～暂时没啥解决办法么？

**Comment by takoyakiwhite** [comment]
已更进此问题。

**Comment by takoyakiwhite** [comment]
留个QQ以查明问题?

**Comment by WUYUEZONG** [comment]
> 留个QQ以查明问题?

1196823283

**Comment by 17772834556** [comment]
> 如题！
> 
> 使用命令开启 hidpi后，关机会有花屏现象。不使用hidpi正常。
> 
> OC版本：最新0.6.4版本
> 
> 机型：Z8 - CT7NT
> 
> 问题（如图）：
> 
> 
> 
> ![WechatIMG8](https://user-images.githubusercontent.com/19921783/102017920-b412e480-3da4-11eb-8f04-2b576e683807.jpeg)
> 
> 

老哥我也是z8我刷的蓝天原厂bios设置里没有那些要关闭的选项啊

**Comment by MichaelPan1026** [comment]
> > 如题！
> > 使用命令开启 hidpi后，关机会有花屏现象。不使用hidpi正常。
> > OC版本：最新0.6.4版本
> > 机型：Z8 - CT7NT
> > 问题（如图）：
> > ![WechatIMG8](https://user-images.githubusercontent.com/19921783/102017920-b412e480-3da4-11eb-8f04-2b576e683807.jpeg)
> 
> 老哥我也是z8我刷的蓝天原厂bios设置里没有那些要关闭的选项啊

可以用eze工具修改bios显示所有选项 或者看网上opencore的教程 只关掉cfg锁就行
