### ISSUE TITLE
请问可以OTA升级到Big Sur吗

### ISSUE THREAD

**Issue by Jarvan0** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#15]
之前用的是CLOVER，现在用了你的OC可以正常引导，现在系统是10.15.4，可以无痛OTA升级到11吗

**Comment by MichaelPan1026** [comment]
应该是可以的。

「Jarvan0 <notifications@github.com>」在 2020年12月19日週六，23:07 寫道：

**Comment by Jarvan0** [comment]
感谢回复，我去试试
