### ISSUE TITLE
内置麦克风不好使呀，睡眠有问题（睡眠就那么滴吧，不修了），麦克风有时间麻烦搞一下。机型NH50RC（z7-ct5na）

### ISSUE THREAD

**Issue by Misakei** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#20]

**Comment by lgh07711** [comment]
[归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
如果是麦克风经常识别不了,试一下这个。自己定制的。

**Comment by lgh07711** [comment]
> _No description provided._

试试看我的

**Comment by MichaelPan1026** [comment]
我是一直用AirPods或者耳机的也一直没注意到这个bug，之前用`alcid=29`是没问题的，刚试了下现在果然不行。上面的可以用。

**Comment by MichaelPan1026** [comment]
> [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> 如果是麦克风经常识别不了,试一下这个。自己定制的。

你可以提交PR给[AppleALC](https://github.com/acidanthera/AppleALC)，这样就可以正常随着主线更新了。

**Comment by lgh07711** [comment]
> > [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> > 如果是麦克风经常识别不了,试一下这个。自己定制的。
> 
> 你可以提交PR给[AppleALC](https://github.com/acidanthera/AppleALC)，这样就可以正常随着主线更新了。

我不知道怎么提交啊，所以就一直自己在用。

**Comment by lgh07711** [comment]
> > [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> > 如果是麦克风经常识别不了,试一下这个。自己定制的。
> 
> 你可以提交PR给[AppleALC](https://github.com/acidanthera/AppleALC)，这样就可以正常随着主线更新了。

还有你知道怎么解决耳机麦克风跟本机的麦克风切换吗？

**Comment by MichaelPan1026** [comment]
> > > [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> > > 如果是麦克风经常识别不了,试一下这个。自己定制的。
> > 
> > 
> > 你可以提交PR给[AppleALC](https://github.com/acidanthera/AppleALC)，这样就可以正常随着主线更新了。
> 
> 还有你知道怎么解决耳机麦克风跟本机的麦克风切换吗？

设置声音输入就可以切换

**Comment by Jarvan0** [comment]
> > > > [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> > > > 如果是麦克风经常识别不了,试一下这个。自己定制的。
> > > 
> > > 
> > > 你可以提交PR给[AppleALC](https://github.com/acidanthera/AppleALC)，这样就可以正常随着主线更新了。
> > 
> > 
> > 还有你知道怎么解决耳机麦克风跟本机的麦克风切换吗？
> 
> 设置声音输入就可以切换

用了上面那个之后内建麦克风有声音了，但是耳机的麦克风又不行了

**Comment by lgh07711** [comment]
> > > > > [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> > > > > 如果是麦克风经常识别不了,试一下这个。自己定制的。
> > > > 
> > > > 
> > > > 你可以提交PR给[AppleALC](https://github.com/acidanthera/AppleALC)，这样就可以正常随着主线更新了。
> > > 
> > > 
> > > 还有你知道怎么解决耳机麦克风跟本机的麦克风切换吗？
> > 
> > 
> > 设置声音输入就可以切换
> 
> 用了上面那个之后内建麦克风有声音了，但是耳机的麦克风又不行了

我这个里面没有添加耳机麦克风的路径。 你之前用的可以用耳机麦克风的驱动发出来看看。

**Comment by Misakei** [comment]
> > > [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> > > 如果是麦克风经常识别不了,试一下这个。自己定制的。
> > 
> > 
> > 你可以提交PR给[AppleALC](https://github.com/acidanthera/AppleALC)，这样就可以正常随着主线更新了。
> 
> 还有你知道怎么解决耳机麦克风跟本机的麦克风切换吗？

谢谢呀，我去试一试。

**Comment by Misakei** [comment]
> 我是一直用AirPods或者耳机的也一直没注意到这个bug，之前用`alcid=29`是没问题的，刚试了下现在果然不行。上面的可以用。

谢谢

**Comment by Misakei** [comment]
> [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> 如果是麦克风经常识别不了,试一下这个。自己定制的。

谢谢

**Comment by Misakei** [comment]
> [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> 如果是麦克风经常识别不了,试一下这个。自己定制的。

这个可以用了，麦克风正常了。

**Comment by HodelY** [comment]
> > > > > > [归档.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6270947/default.zip)
> > > > > > 如果是麦克风经常识别不了,试一下这个。自己定制的。
> > > > > 
> > > > > 
> > > > > 你可以提交PR给[AppleALC](https://github.com/acidanthera/AppleALC)，这样就可以正常随着主线更新了。
> > > > 
> > > > 
> > > > 还有你知道怎么解决耳机麦克风跟本机的麦克风切换吗？
> > > 
> > > 
> > > 设置声音输入就可以切换
> > 
> > 
> > 用了上面那个之后内建麦克风有声音了，但是耳机的麦克风又不行了
> 
> 我这个里面没有添加耳机麦克风的路径。 你之前用的可以用耳机麦克风的驱动发出来看看。

老哥我跟你一样的机型，你的外接显示器显示正常嘛，可以把你的efi发我一份吗，可以有偿

**Comment by HodelY** [comment]
> 

联系方式qq2523929589
