### ISSUE TITLE
硬件以及功能使用问题

### ISSUE THREAD

**Issue by liuweeno** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#21]
请问这个efi文件适配情况怎么样，Wi-Fi、蓝牙可以用吗？注入三码后handoff可以用吗？

**Comment by MichaelPan1026** [comment]
没有对英特尔网卡的蓝牙WiFi做支持，但是用户反馈手动添加驱动可用。

liuweeno ***@***.***> 於 2021年4月22日 週四 下午12:51寫道：

**Comment by liuweeno** [comment]
请问添加对应驱动后，handoff可以用吗？现在使用了heliport的方法是可以用的了

**Comment by lgh07711** [comment]
> 请问添加对应驱动后，handoff可以用吗？现在使用了heliport的方法是可以用的了

可以用。

**Comment by liuweeno** [comment]
> > 请问添加对应驱动后，handoff可以用吗？现在使用了heliport的方法是可以用的了
> 
> 可以用。

真的吗？不换网卡能实现handoff是吗？！请留一个联系方式可以吗？

**Comment by lgh07711** [comment]
> > > 请问添加对应驱动后，handoff可以用吗？现在使用了heliport的方法是可以用的了
> > 
> > 
> > 可以用。
> 
> 真的吗？不换网卡能实现handoff是吗？！请留一个联系方式可以吗？

![Cache_476b178c00489db8](https://user-images.githubusercontent.com/54872602/116171721-e281d280-a73b-11eb-84b6-0f2c05453d9e.jpg)
![Cache_476b178c00489db8](https://user-images.githubusercontent.com/54872602/116171734-eb72a400-a73b-11eb-9fbd-bb342eaf31d8.jpg)

**Comment by lgh07711** [comment]
> > > 请问添加对应驱动后，handoff可以用吗？现在使用了heliport的方法是可以用的了
> > 
> > 
> > 可以用。
> 
> 真的吗？不换网卡能实现handoff是吗？！请留一个联系方式可以吗？

![Cache_476b178c00489db8](https://user-images.githubusercontent.com/54872602/116171792-0b09cc80-a73c-11eb-8f00-71c2a3f84a22.jpg)
![Cache_537f9f8f17638ca](https://user-images.githubusercontent.com/54872602/116171794-0cd39000-a73c-11eb-978c-24e3347c95a1.jpg)

**Comment by liuweeno** [comment]
是的，这个efi配置文件非常棒
