### ISSUE TITLE
添加仿冒部件

### ISSUE THREAD

**Issue by lgh07711** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#23]
![image](https://user-images.githubusercontent.com/54872602/116786444-34767f80-aad1-11eb-9477-ed5c8dc06341.png)
添加仿冒部件， 按电源键3秒左右。 出现关机菜单。
[SSDT-APMC.aml.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/6409789/SSDT-APMC.aml.zip)

**Comment by MichaelPan1026** [comment]
已合并，谢谢
