### ISSUE TITLE
hdmi可能不能使用

### ISSUE THREAD

**Issue by bchaoqun** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#28]
在我的 雷神911mt i7-9750h gtx1650 上himi不可用，复现：cfg clock未关闭；
请问你的电脑hdmi可以用吗

**Comment by MichaelPan1026** [comment]
不可以，HDMI 输出口是独显输出口。

bchaoqun ***@***.***> 於 2021年5月19日 週三 上午11:36寫道：

**Comment by bchaoqun** [comment]
感谢
