### ISSUE TITLE
换了BCM94352z （DW1560）网卡有驱动需要删减吗？

### ISSUE THREAD

**Issue by WUYUEZONG** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#29]
都说BCM94352z免驱，换了之后wifi蓝牙不能正常用，windows下可以。

**Comment by MichaelPan1026** [comment]
添加 https://github.com/acidanthera/AirportBrcmFixup, https://github.com/acidanthera/BrcmPatchRAM 这两个驱动

**Comment by WUYUEZONG** [comment]
**感谢大佬啊！**

😓 一开始没认真看文档，差点回不来了。

> 添加目录是这样的，给其他人参考下。

![image](https://user-images.githubusercontent.com/19921783/120172875-10c06980-c236-11eb-8b35-897677225652.png)
