### ISSUE TITLE
大家的开机时间都要多久啊。

### ISSUE THREAD

**Issue by lgh07711** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#30]
大家的开机时间都要多久啊。 我的大概30～40秒。 我看好像好多人就十几秒。

**Comment by MichaelPan1026** [comment]
Big Sur的时候很快。

**Comment by lgh07711** [comment]
> Big Sur的时候很快。

我的就是啊。11.4 (20F71)怎么这么慢。😭

**Comment by MichaelPan1026** [comment]
> > Big Sur的时候很快。
> 
> 我的就是啊。11.4 (20F71)怎么这么慢。😭

可以加启动参数跑码看看有什么不对劲。
