### ISSUE TITLE
蓝牙耳机的麦克风没有声音输入

### ISSUE THREAD

**Issue by codefish-y** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#31]
连上beats之后，自动切换到蓝牙耳机的麦克风输入了，但是听不到我输入的声音,内建的麦克风有用，可以用耳机的输出，内建的输入，就是用不了耳机的输入，不知道大佬能否修复这个问题，不清楚是蓝牙驱动的问题还是什么其他问题，蓝牙驱动用的是z大的https://github.com/OpenIntelWireless/IntelBluetoothFirmware
<img width="668" alt="截屏2021-06-12 下午3 28 08" src="https://user-images.githubusercontent.com/26838085/121768809-ce325180-cb92-11eb-94fe-92a14b4c2bae.png">

**Comment by MichaelPan1026** [comment]
尝试联系驱动提供方。

**Comment by codefish-y** [comment]
> 尝试联系驱动提供方。

好的，还有想请问一下，现在如果想更到Monterey的话，内置喇叭不可用指的是仅内置扬声器吗？蓝牙问题已经有折中解决方案了，但是还不完美

**Comment by MichaelPan1026** [comment]
> 
> 
> > 尝试联系驱动提供方。
> 
> 好的，还有想请问一下，现在如果想更到Monterey的话，内置喇叭不可用指的是仅内置扬声器吗？蓝牙问题已经有折中解决方案了，但是还不完美

内置喇叭已经可以用了。~~，启动参数添加`-lilubetaall`~~

**Comment by codefish-y** [comment]
> > > 尝试联系驱动提供方。
> > 
> > 
> > 好的，还有想请问一下，现在如果想更到Monterey的话，内置喇叭不可用指的是仅内置扬声器吗？蓝牙问题已经有折中解决方案了，但是还不完美
> 
> 内置喇叭已经可以用了，启动参数添加`-lilubetaall`

那现在开机还有读条很慢的情况吗

**Comment by MichaelPan1026** [comment]
> 
> 
> > > > 尝试联系驱动提供方。
> > > 
> > > 
> > > 好的，还有想请问一下，现在如果想更到Monterey的话，内置喇叭不可用指的是仅内置扬声器吗？蓝牙问题已经有折中解决方案了，但是还不完美
> > 
> > 
> > 内置喇叭已经可以用了，启动参数添加`-lilubetaall`
> 
> 那现在开机还有读条很慢的情况吗

一般般
