### ISSUE TITLE
HDMI 不工作

### ISSUE THREAD

**Issue by xkeyC** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#32]
我是神舟 z7m-ct5na，已刷蓝天 bios，所有设置已按照要求更改，启动后几乎一切正常，但是唯独 HDMI 不工作。

我确信 hdmi 走的核显，但和显示器连接后卡了几下，之后什么反应都没有。

google 了一些方法似乎都没啥效果，大佬有什么好方法么？

**Comment by MichaelPan1026** [comment]
我机型 minidp 是走核显，HDMI 没办法测试，抱歉了。

「xkeyC ***@***.***>」在 2021年8月9日 週一，16:53 寫道：
