### ISSUE TITLE
关闭cfg lock 后卡logo

### ISSUE THREAD

**Issue by JiangSongBai** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#38]
按照readme的方法关闭cfg lock后，将配置文件config.plist中AppleCpuPmCfgLock和AppleXcpmCfgLock两项 Quirks 禁用之后，开机一直卡logo，无法开机

**Comment by JiangSongBai** [comment]
按照文档的方法无法关闭CFG LOCK，最后用ru.efi关闭的

**Comment by MichaelPan1026** [comment]
可能是不同机型偏移量不同了，我看的同模具的两个机子偏移量都是`0x3E`我就写上了~

**Comment by JiangSongBai** [comment]
偏移量是0x3E，但就是改不了，z7ct7nt,官方原版的bioS

**Comment by chengnan049** [comment]
我这里附上一个 [`NH5xDB / DBQ / NH77DBQ/ NH5xDE / DEQ / NH77DEQ`](http://repo.palkeo.com/clevo-mirror/NHxxDBx_DEx/) 的偏移量，`0x3E` 希望能帮到

>0x1616B9 		One Of: CFG Lock, VarStoreInfo (VarOffset/VarName): 0x3E, VarStore: 0x3, QuestionId: 0x186, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 8C 03 8D 03 86 01 03 00 3E 00 10 10 00 01 00}
