### ISSUE TITLE
虚拟机无法正常运行

### ISSUE THREAD

**Issue by JiangSongBai** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#39]
virtual box和docker都不能正常运行

**Comment by MichaelPan1026** [comment]
Docker 可以正常运行，VirtualBox 我认为是软件兼容问题，我也修复不了。
![截圖 2021-10-08 上午1 29 37](https://user-images.githubusercontent.com/26241105/136435206-09130c82-1cf9-480c-bd44-448ac419588e.png)

**Comment by JiangSongBai** [comment]
docker 你用的哪个版本？

**Comment by MichaelPan1026** [comment]
> 
> 
> docker 你用的哪个版本？

官网下载的最新版

**Comment by JiangSongBai** [comment]
我也是用的官网最新版，起不来，一直starting。11.6的系统+0.7.2oc

**Comment by JiangSongBai** [comment]
docker重装几次好了，虚拟机是virtual box的锅，vmware没毛病
