### ISSUE TITLE
Monterey 优化 支持网卡wifi 蓝牙 HEVC

### ISSUE THREAD

**Issue by xqdd** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#41]
感谢作者的Repo，在这里分享一下我的优化：  
1. 设备属性去除`AAPL,snb-platform-id`，可开启HEVC

2. 安装[intel的网卡驱动和蓝牙驱动](https://github.com/OpenIntelWireless)，wifi需要使用[软件连接 ](https://github.com/OpenIntelWireless/HeliPort/releases)

3. 型号换成`MacBookPro16,4`，CPU也是i7 9750H，感觉兼容性会好一些  

[EFI.7z](https://github.com/XQDD/HackIntosh-Hasee-G8-CT7NA/blob/master/EFI.7z)

<img width="896" alt="截屏2022-01-16 下午9 28 27" src="https://user-images.githubusercontent.com/20871761/149661963-78f785f1-9bd1-4604-8f8b-208b8b134c7c.png">
<img width="666" alt="截屏2022-01-16 下午9 38 24" src="https://user-images.githubusercontent.com/20871761/149662416-ec37475c-4da2-4993-b558-1074db205aee.png">
<img width="426" alt="截屏2022-01-16 下午9 39 15" src="https://user-images.githubusercontent.com/20871761/149662588-b61b05bf-6709-4fec-9066-eb82809bcea3.png">

**Comment by qianmo-xw** [comment]
确实，我现在有蓝牙不能用的问题。wifi用那个原生驱动偶尔会报错，就是不用软件的那个驱动

**Comment by qianmo-xw** [comment]
确实，原作者的有蓝牙不能驱动的问题。wifi用那个驱动我偶现在会报错，就是不用那个软件的问题。明天我试一下这个

**Comment by MichaelPan1026** [comment]
感谢分享。第一条我找时间合并一下，第二条我在用博通网卡，第三条更换该型号会导致外接显示器没有视频输出。

**Comment by qianmo-xw** [comment]
> 

合并了吗老大

**Comment by Misakei** [comment]
![image](https://user-images.githubusercontent.com/33886929/151860751-e0d008f3-d14d-4104-9d64-07fdebdd705d.png)
实测,这么改有用.

**Comment by MichaelPan1026** [comment]
> > 
> 
> 合并了吗老大

已合并 059cf96
