### ISSUE TITLE
minidp需要从windows重启过来才能驱动

### ISSUE THREAD

**Issue by nbb2025** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#44]
遇到很奇怪的问题：每次需要驱动显示器时都需要从windows重启过来才能驱动，直接启动macos时显示器一点反应都没有，framebuffer-con1的参数尝试着换了几次都无果，可能是自己也比较菜
![截屏2022-02-22 10 48 14](https://user-images.githubusercontent.com/43722192/155054317-ffd4b241-9739-4c77-9b19-0a0a4ebc8a06.png)
![截屏2022-02-22 10 48 35](https://user-images.githubusercontent.com/43722192/155054334-b16e05b3-8f49-45ea-9454-e935cdfddbdd.png)

**Comment by liuweeno** [comment]
请问你是什么型号

**Comment by nbb2025** [comment]
> 

g8-ct7na，机型设置的是mbp16,1

**Comment by MichaelPan1026** [comment]
我这边测试的是驱动不了16英寸macOS机型的外接显示器。
