### ISSUE TITLE
大佬，请问我电脑为神舟战神Z7-CT5NA可以用这个安装吗？

### ISSUE THREAD

**Issue by iClouds** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#45]
神舟NH5X_7xRCx,RDx笔记本电脑

没有动过bios全部是系统预装配置，需要先升级或解锁bios吗？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by iClouds** [comment]
安装好了 谢谢大佬（但我开机音效怎么都好不了

**Comment by RT237297** [comment]
可以提供一下efi嘛老哥 我也是NH5X_7xRCx,RDx  Z7-CT5NA

**Comment by RT237297** [comment]
跪求
