### ISSUE TITLE
使用0771引导不了catalina,引导界面没有引导选项。

### ISSUE THREAD

**Issue by Misakei** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#46]
使用0771引导不了catalina,引导界面没有引导选项。0680有引导选项可以引导，然后我装bigsur，安装引导0771也不显示引导，0680可以正常显示，正常引导。macos大版本和opencore版本之间有兼容性问题？有没有什么建议？

**Comment by MichaelPan1026** [comment]
opencore升级的时候确实改变了一些兼容新版本macOS的选项，但是对旧版本macOS不知道兼不兼容了
