### ISSUE TITLE
添加intel蓝牙驱动后无法启动

### ISSUE THREAD

**Issue by qinglt** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#47]

**Comment by MichaelPan1026** [comment]
我不用intel蓝牙，不能帮你测试。

**Comment by qianmo-xw** [comment]
> No description provided.

无问题啊![image](https://user-images.githubusercontent.com/83547396/192139660-9bed90f0-a32c-4213-bde9-43311b20e14d.png)
monterey启用这两个试试
![image](https://user-images.githubusercontent.com/83547396/192139677-ef51143e-3505-46f8-85a9-ef4d7bb48a53.png)
