### ISSUE TITLE
雷神911mt 基本完美

### ISSUE THREAD

**Issue by bchaoqun** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#48]
模具相同 i7-9750h gtx1650，目前修改后正常项目：蓝牙、WiFi、睡眠(测试睡眠不掉电，但是唤醒之后键盘的不亮)、键盘灯、触摸板(支持多指)、HDMI(可以外接1920*1080的，带鱼屏不可以，2K 4K没有测试)、音响(包括耳机)
我该如何分享我的efi

**Comment by MichaelPan1026** [comment]
你可以在这下面贴一个压缩包

**Comment by bchaoqun** [comment]
[EFI.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/8974033/EFI.zip)
后缀改成.7z  github不支持贴7z格式的文件

**Comment by MichaelPan1026** [comment]
`SSDT-EC-USBX.aml`  和 `SSDT-AWAC-DISABLE.aml` 是怎么制作的？

**Comment by bchaoqun** [comment]
> `SSDT-EC-USBX.aml` 和 `SSDT-AWAC-DISABLE.aml` 是怎么制作的？

这俩是没用的，昨天更新0.8.1的时候多余了

**Comment by MichaelPan1026** [comment]
我看了下你这个没有相关的睡眠fix啊，你是怎么把睡眠搞好的？现在我这个是玄学睡眠，时好时坏。

**Comment by bchaoqun** [comment]
> 我看了下你这个没有相关的睡眠fix啊，你是怎么把睡眠搞好的？现在我这个是玄学睡眠，时好时坏。

这个也是玄学，与其说是玄学不如说是我不懂，这个efi是从别人那里拿的，他的efi不能支持触摸板和hdmi，我根据其他的可以支持触摸板和hdmi的改的，原理我也不懂。但是确实是可以支持睡眠，目前我测试的每次都能成功睡眠

**Comment by MichaelPan1026** [comment]
目前我这个触摸板是没问题的，每个机型的外接视频输出还是不一样，我的是minidp。睡眠实在搞不明白。
