### ISSUE TITLE
首先感谢大佬的分享，其次我想问一下可以使用扩展屏幕吗？我通过dp接口外接显示器系统会卡顿一会然后就没反应了

### ISSUE THREAD

**Issue by manton94** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#6]

**Comment by MichaelPan1026** [comment]
我的机器（z8-ct5n1）minidp 接口输出正常，看起来你机器的dp接口是独显输出。试试 TypeC 和 HDMI 接口，要找核显输出的。

**Comment by AJavaDeveloper** [comment]
老哥~想问一下睡眠问题有没有解决~ 看你更新很快加入了intel网卡驱动 还有就是能不能分享一哈G8-CT7NA 的蓝天BIOS

**Comment by MichaelPan1026** [comment]
> 老哥~想问一下睡眠问题有没有解决~ 看你更新很快加入了intel网卡驱动 还有就是能不能分享一哈G8-CT7NA 的蓝天BIOS

睡眠是用的 AOAC 睡眠而非传统睡眠。BIOS 在这：ftp://ftp.clevo.com.tw/ALLBIOS/NH5x_70_RDx_RCx_RAx_RHx(Q)/NHxxRC_RDx_B10713.zip

**Comment by manton94** [comment]
> 
> 
> 我的机器（z8-ct5n1）minidp 接口输出正常，看起来你机器的dp接口是独显输出。试试 TypeC 和 HDMI 接口，要找核显输出的。

![图片](https://user-images.githubusercontent.com/46070956/98318378-75597400-2019-11eb-814d-b57394f28c92.png)
我的机器是g8-ct7nk  ,图上是在windows上通过dp外接的，看起来是核显输出的吧

**Comment by MichaelPan1026** [comment]
> > 我的机器（z8-ct5n1）minidp 接口输出正常，看起来你机器的dp接口是独显输出。试试 TypeC 和 HDMI 接口，要找核显输出的。
> 
> ![图片](https://user-images.githubusercontent.com/46070956/98318378-75597400-2019-11eb-814d-b57394f28c92.png)
> 我的机器是g8-ct7nk ,图上是在windows上通过dp外接的，看起来是核显输出的吧

这个图不准，推荐看 Windows 显示器设置里面的详情。而且图上显示的是 HDMI 外接。

**Comment by manton94** [comment]
> 这个图不准，推荐看 Windows 显示器设置里面的详情。而且图上显示的是 HDMI 外接。

![图片](https://user-images.githubusercontent.com/46070956/98322164-c0778500-2021-11eb-9fd2-efd0729497c1.png)

这个吗

**Comment by MichaelPan1026** [comment]
> > 这个图不准，推荐看 Windows 显示器设置里面的详情。而且图上显示的是 HDMI 外接。
> 
> ![图片](https://user-images.githubusercontent.com/46070956/98322164-c0778500-2021-11eb-9fd2-efd0729497c1.png)
> 
> 这个吗

对

**Comment by manton94** [comment]
在mac下也是这样连接的，可是就是不行。我再研究一下吧，感谢大佬！

**Comment by MichaelPan1026** [comment]
> 在mac下也是这样连接的，可是就是不行。我再研究一下吧，感谢大佬！

你现在是 minidp 连接的？

**Comment by manton94** [comment]
> 你现在是 minidp 连接的？

是的啊
