### ISSUE TITLE
补充

### ISSUE THREAD

**Issue by lgh07711** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#7]
我的电脑型号是神舟Z7-CT7NA，蓝天模具型号：NH50RC。自己更换了4K屏。定制了ALC可以驱动内置麦克风。我还修改了VirtualSMC.kext用来支持我的蓝牙鼠标。但这个并不通用需要根据自己的鼠标进行修改。另附上根据你的config.plist修改的支持4K的config.plist

另外方便加一下QQ吗？734416637。
[AppleALC.kext.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/5507877/AppleALC.kext.zip)
[VirtualSMC.kext.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/5507879/VirtualSMC.kext.zip)
[config.plist.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/5507884/config.plist.zip)
<img width="668" alt="粘贴的图形-2" src="https://user-images.githubusercontent.com/54872602/98496253-2d865700-227c-11eb-9475-93632ba283bb.png">
<img width="668" alt="粘贴的图形-3" src="https://user-images.githubusercontent.com/54872602/98496265-370fbf00-227c-11eb-93ba-86aa4fc32b50.png">

**Comment by MichaelPan1026** [comment]
4K屏的部分可以合并。alcid=29 内置麦克风可以正常工作啊。VirtualSMC的部分恐怕不行，毕竟这个要随着OpenCore版本更新的。

**Comment by lgh07711** [comment]
可能机型之间还是有不一样的， 并且NH50BD和我的声卡型号一样都是293，我定制的他用不了。我这台机的麦克风很难驱动到。 10次能驱动两次就不错了。

2020年11月9日 11:33，MichaelPan1026 <notifications@github.com<mailto:notifications@github.com>> 写道：



4K屏的部分可以合并。alcid=29 内置麦克风可以正常工作啊。VirtualSMC的部分恐怕不行，毕竟这个要随着OpenCore版本更新的。

**Comment by lgh07711** [comment]
现在你的机器上可以正常睡眠吗？我使用你的不行，无法进入睡眠状态。

**Comment by MichaelPan1026** [comment]
> 现在你的机器上可以正常睡眠吗？我使用你的不行，无法进入睡眠状态。

现在应该是用的是 AOAC 睡眠，键盘灯还亮着的。正常的睡眠我也不会弄。

**Comment by lgh07711** [comment]
我总觉得都没有进入睡眠，硬盘指示灯还会闪烁。我之前的OC引导每次开机后可以正常睡眠并唤醒，但是睡眠后再次唤醒就不行了。弄了N久都没弄好。

**Comment by lgh07711** [comment]
<img width="1280" alt="WX20201109-195053@2x" src="https://user-images.githubusercontent.com/54872602/98537967-099b3380-22c5-11eb-92f2-2969eb7d91b3.png">
<img width="1280" alt="WX20201109-195102@2x" src="https://user-images.githubusercontent.com/54872602/98537977-0d2eba80-22c5-11eb-8d2c-1a80ea20368b.png">
你这样设置看一下能不能正常睡眠。还有你的SSDT-XSPI.aml这个是什么作用的啊，没查到。我的这样首次可以正常睡眠。

**Comment by MichaelPan1026** [comment]
> <img alt="WX20201109-195053@2x" width="1280" src="https://user-images.githubusercontent.com/54872602/98537967-099b3380-22c5-11eb-92f2-2969eb7d91b3.png">
> 
> <img alt="WX20201109-195102@2x" width="1280" src="https://user-images.githubusercontent.com/54872602/98537977-0d2eba80-22c5-11eb-8d2c-1a80ea20368b.png">
> 
> 你这样设置看一下能不能正常睡眠。还有你的SSDT-XSPI.aml这个是什么作用的啊，没查到。我的这样首次可以正常睡眠。

这个也是添加缺失的组件

**Comment by MichaelPan1026** [comment]
怀疑是 Clevo bios 的问题 睡眠无法修复了
