### ISSUE TITLE
应该是有关于Clevo bios设置。

### ISSUE THREAD

**Issue by lgh07711** [MichaelPan1026/Clevo-NH50-NH70-Hackintosh#9]
bios中有一项System Time and Alarm Source设置我们这个机型默认的是ACPI Time and Alarm Device，NH50BD这个机型的默认值是Legacy RTC，这个机型可以正常睡眠。但是我调整了Legacy RTC之后也不能正常睡眠。

**Comment by MichaelPan1026** [comment]
关于 RTC 的这方面蓝天设计的可能不规范。我也注意到这个了，而且 SSDT 中没有 AWAC 这个设备。

lgh07711 <notifications@github.com> 於 2020年11月15日 週日 下午6:53寫道：

**Comment by lgh07711** [comment]
我现在想归纳两个机型bios中可能影响睡眠的设置的不一样的地方。但是项目太多。我对bios中每一项设置所表达的意思也不太了解，只能按照字面意思去体会，不知道你有什么好的方法吗。并且他那个机型，可以用快捷键调节键盘背光亮度还有颜色。

**Comment by MichaelPan1026** [comment]
用这个 efi 就可以正常睡眠和调节键盘背光亮度颜色吗？可以在这里发一份 DSDT。

**Comment by lgh07711** [comment]
不是用这个EFI。我问他要一下DSDT文件，之前给我过，我弄丢了。

**Comment by MichaelPan1026** [comment]
> 不是用这个EFI。我问他要一下DSDT文件，之前给我过，我弄丢了。

要是之前的那个 Clover 的话，其他的机器也可以睡眠的。

**Comment by lgh07711** [comment]
也是用的OC引导的。只不过不是用你这个。

**Comment by lgh07711** [comment]
[acpi_dsdt.aml.zip](https://github.com/MichaelPan1026/Clevo-NH50-NH70-Hackintosh/files/5543544/acpi_dsdt.aml.zip)

**Comment by MichaelPan1026** [comment]
这个机器的 AWAC 设备是正常的 别的机型没有
![截屏2020-11-16 下午9 19 18](https://user-images.githubusercontent.com/26241105/99257086-652f6900-2851-11eb-9e2b-29ed151825f7.png)
